# Generated by Django 4.2.4 on 2023-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('ModifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('EmployeeDepartment', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateTimeField(auto_now_add=True)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
