# Generated by Django 4.2.4 on 2023-08-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLists',
            fields=[
                ('DeptListId', models.AutoField(primary_key=True, serialize=False)),
                ('DeptListName', models.CharField(max_length=500)),
            ],
        ),
    ]
