# Generated by Django 4.2.4 on 2023-08-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_departmentlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFileName',
        ),
    ]
